'use client';

import { useState } from 'react';

interface Props {
  userId: string;
}

export function ChatLogExport({ userId }: Props) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      // In a real implementation, fetch from token_usage_log
      // For now, generate a sample markdown export
      const markdown = `# Opus8 Chat Log
**User ID:** ${userId}
**Export Date:** ${new Date().toISOString()}
**Model:** Claude Opus 8

---

## Session Summary

Total tokens used, costs, and conversation history would appear here.

---

## Conversation

*Chat logs exported from the Opus8 Desktop App.*

---

*Generated by Opus8 Platform — claude.ai-powered coding.*
`;

      const blob = new Blob([markdown], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `opus8-chat-${new Date().toISOString().slice(0, 10)}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="btn-secondary w-full text-sm"
    >
      {exporting ? 'Exporting...' : '📥 Export Chat Logs (.md)'}
    </button>
  );
}
